### ISSUE TITLE
CloudSurph default install - ubuntu-18.04-x86_64 - trouble

### ISSUE THREAD

**Issue by lk29** [amnezia-vpn/desktop-client#11]
The reason is that when executing the command
apt install -y docker.io curl

installing libssl1.1
requires an answer

If you start manually executing the command, we see a question on the screen

![amnezia_trouble](https://user-images.githubusercontent.com/12291632/111132929-c2d38800-859b-11eb-8e3b-e0bd79c355ba.gif)

**Comment by pokamest** [comment]
Any ideas how to automate it?

**Comment by lk29** [comment]
Tonight I will try different ways
I'll write the result here.

**Comment by lk29** [comment]
Where is the script that is running on the server located ?

**Comment by pokamest** [comment]
https://github.com/amnezia-vpn/desktop-client/tree/dev/client/server_scripts
https://github.com/amnezia-vpn/desktop-client/blob/dev/client/server_scripts/setup_shadowsocks_server.sh

**Comment by lk29** [comment]
no fixes added yet
decision
1) reinstall the ubuntu18 distribution
2) login via ssh to your vps
3) run the command
apt update; DEBIAN_FRONTEND = 'noninteractive' apt-get install -yq libssl1.1;

This will probably help on other hosts as well when using ubuntu18

**Comment by pokamest** [comment]
Great, I will include solution the next build

**Comment by pokamest** [comment]
Issue fixed since 1.5.3
