### ISSUE TITLE
MacOS Monterey constant crashes

### ISSUE THREAD

**Issue by Notespeak** [amnezia-vpn/desktop-client#110]
Greetings, the new amezia client - 2.1.0 constantly crashes on MacOS Monterey 12.5.1, because of permission issues. Here is a shortened report on this issue.

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               AmneziaVPN [29846]
Path:                  /Applications/AmneziaVPN.app/Contents/MacOS/AmneziaVPN
Identifier:            com.amnezia.AmneziaVPN
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-09-08 14:31:15.7047 +0300
OS Version:            macOS 12.5.1 (21G83)
Report Version:        12
Bridge OS Version:     6.6 (19P6066)
Anonymous UUID:        FE43889F-BF09-75E4-513C-48FD9EA56136

Sleep/Wake UUID:       EEA4BE36-88B9-4908-84BA-0CAA06E534BA

Time Awake Since Boot: 230000 seconds
Time Since Wake:       16 seconds

System Integrity Protection: enabled

Crashed Thread:        20  Dispatch queue: com.apple.root.default-qos

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace TCC, Code 0 
This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an com.apple.security.device.camera key with a string value explaining to the user how the app uses this data.

**Comment by pokamest** [comment]
Fixed in release 2.1.2.3
Please check - https://github.com/amnezia-vpn/desktop-client/releases/download/2.1.2/AmneziaVPN_2.1.2.3.dmg
