### ISSUE TITLE
Get an error while setting up the server (windows server 2019)

### ISSUE THREAD

**Issue by mahsamcse** [amnezia-vpn/desktop-client#116]
Get an error while setting up the server (windows server 2019)

error 1 :  server ip address just type ip
![2022-09-30_00-23-14](https://user-images.githubusercontent.com/114700120/193140164-464f2758-521d-4a1c-815c-f80ec2073065.png)

error 2 : server ip address type ip + port
![2022-09-30_00-26-22](https://user-images.githubusercontent.com/114700120/193140649-e2cee647-c832-4c1b-a1fe-5488cceff772.png)

please guide me
Thanks

**Comment by omortie** [comment]
I think you had entered wrong credentials or you don't have access to your server, please check if you can connect to your server with ssh from console and try again

**Comment by mahsamcse** [comment]
Thank you for your answer
I enter the username and password that I use to connect to the server through remote desktop
Am I entering the wrong information?
I only have this information from my server

**Comment by omortie** [comment]
windows server 2019 is not supported by this application, you should switch your server OS to some linux like ubuntu 16LTS or similar options
