### ISSUE TITLE
Application window disappeared, app is running (Mac OS)

### ISSUE THREAD

**Issue by advoretsky** [amnezia-vpn/desktop-client#14]
After some time (macbook was closed) I can't see application window. App is running (IP is detected as of vpn server). Maintenancetool says "app is running". Attempt to run app again doesn't help

**Comment by pokamest** [comment]
Tray icon also disappeared?

**Comment by advoretsky** [comment]
Tray icon was on place. I just didn't notice it's there.

**Comment by konstantinLyang** [comment]
I also have that problem!!! How to fix it???????

**Comment by konstantinLyang** [comment]
@advoretsky did u solve the problem?

**Comment by konstantinLyang** [comment]
why issue was closed??? I hate that issue so match. I tried to reinstall - not help, relaunch - no help. How to f*king fix it??

**Comment by routers-guru** [comment]
@konstantinLyang as you can see from the thread I missed the tray icon (looked for the app itself). So it was not a real issue – having a tray icon is enough.
