### ISSUE TITLE
Not work in macos

### ISSUE THREAD

**Issue by antirius** [amnezia-vpn/desktop-client#16]
If you specify a list of allowed sites, then only they work. The rest of the network does not work at all until the wi-fi is restarted.
And sometimes the network just stops working. Then just disconnect and reconnect wi-fi. Mac OS 11.3

**Comment by pokamest** [comment]
What is build version? Latest releases are 1.6.2
Please join to https://t.me/amnezia_vpn_en and send log files

**Comment by pokamest** [comment]
Closed with no response.
Join to https://t.me/amnezia_vpn_en for technical support.
