### ISSUE TITLE
Wrong scale of main window at HiDPI displays on Windows

### ISSUE THREAD

**Issue by inoyakaigor** [amnezia-vpn/desktop-client#34]
I have nothing to add to title except screenshot:

<img src="https://user-images.githubusercontent.com/1235286/130646415-76b1d009-40c3-4d2c-bc61-7c1a19d2f69f.png" height="480">

**Comment by boscogh** [comment]
works for me with env var QT_AUTO_SCREEN_SCALE_FACTOR=1
take a look https://doc.qt.io/qt-5/highdpi.html
probably should set -platform windows:dpiawareness=0 during build time for all

**Comment by pokamest** [comment]
Please check how it looks in Amnezia 2.0 - UI was completely rewritten

**Comment by pokamest** [comment]
Fixed in Amnezia 2.x
