### ISSUE TITLE
v2.0.1 AmneziaVPN-service fails to start with error 1053 

### ISSUE THREAD

**Issue by boscogh** [amnezia-vpn/desktop-client#46]
Works fine if started as a console app with admin privileges
Have tried to install/remove several times, also increased "ServicesPipeTimeout" registry key - no help

**Comment by boscogh** [comment]
issue remains on 2.0.6

**Comment by pokamest** [comment]
Please attach logs or send directly via telegram https://t.me/amnezia_vpn_en

**Comment by boscogh** [comment]
the problem is that service does not create any logs, it just fails to start

**Comment by pokamest** [comment]
What is Windows version? You can try to start service by hands from cmd (with admin privil) by passing argument "-s", service will be launched as regular process, and then you can check if it crashed, or something else.

**Comment by boscogh** [comment]
C:\WINDOWS\system32>ver
Microsoft Windows [Version 10.0.19044.1466]

C:\Program Files\AmneziaVPN>AmneziaVPN-service.exe -s
2022-01-26 07:41:49 info Started as console application
<started normally as console app>

C:\Program Files\AmneziaVPN>AmneziaVPN-service.exe
2022-01-26 07:55:00 info Started as system service
The service AmneziaVPN-service could not start
<no other logs>

**Comment by boscogh** [comment]
I use the process as console app, it works just fine (as I said at the beginning). But it's not convinient to run it manually
as service it just won't start at all. the error number from event viewer is 1053

**Comment by pokamest** [comment]
Btw, it's not possible to start AmneziaVPN-service.exe (without -s arg) as a service from cmd, only system able to launch service.
Another question is why service crashing on your Windows.
You can try to stop and remove service from admin cmd, reboot, and then reinstall app:
```
sc stop AmneziaVPN-service
sc delete AmneziaVPN-service
```

**Comment by boscogh** [comment]
I reinstalled it already several times (multiple 2.0.x realeases). 
before 2.0 release, it was working fine, so might be just building flags are different

**Comment by boscogh** [comment]
Tested on 2.0.8, still the same, even again did that you recommend with stop and delete, reboot and reinstall - nothing changed. Could you please mb create a debug build of service app, so it at least print some trace messages in the log?
I see on stackexchange they say this could be the problem with unhandled exception, so mb make some more catch sections and trace the error too?

**Comment by boscogh** [comment]
I finally got it. Sorry for taking your time, it was a dll conflict on my side. I reinstalled VC runtime libs from there
https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
reordered file paths (this may be a no-op), rebooted and now service works just fine, right after windows start.

**Comment by pokamest** [comment]
Actually it's already distributed with app - you can find vc_redist.x64.exe installer in the app folder. The issue is the app can't determine if vcredist reinstall required.

**Comment by R12M** [comment]
Приложение не устанавливается. (AmneziaVPN_2.0,8,3_*64,exe - Системная ошибка.  Не удается продолжить выполнение кода, поскольку система не обнаружила MSVCP140,dll. Для устранения этой проблемы попробуйте переустановить программу)  -  Неоднократно переустанавливал, но всё равно не работает. Что делать?

**Comment by MikadoAndru** [comment]
> I finally got it. Sorry for taking your time, it was a dll conflict on my side. I reinstalled VC runtime libs from there https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170 reordered file paths (this may be a no-op), rebooted and now service works just fine, right after windows start. You probably may consider to distribute the required MSVC libs with your code too :)
> 
> it works fine with MSVCP140.dll v14.30.30708.0

do not choose between the 32bit (x86) or the 64bit (x64), **just install both if you have a 64bit (x64) based system.**
