### ISSUE TITLE
[Feature request] Update IPs for hosts

### ISSUE THREAD

**Issue by Nexen23** [amnezia-vpn/desktop-client#48]
Some sites change it's IPs without changing host name, which means VPN stops working for them and you have to manually re-add already existing host name.
It would be nice if Amnezia could recheck hosts ip's in the background and silently update them

**Comment by pokamest** [comment]
Fixed in 2.0.8
https://github.com/amnezia-vpn/desktop-client/releases/tag/2.0.8
