### ISSUE TITLE
[Feature request] WireGuard over ShadowSocks

### ISSUE THREAD

**Issue by kobin23** [amnezia-vpn/desktop-client#50]
In some countries,  in particular in Uzbekistan Wireguard is blocked. It would be nice if it were possible to use it with Shadowsocks

**Comment by pokamest** [comment]
Wireguard working using UDP protocol, but ShadowSocks is TCP transport, so it's impossible to wrap WireGuard by ShadowSocks.
But we going to test scheme WireGuard over Cloak.
Meanwhile you can use Cloak container in Amnezia - it working fine and able to pass DPI
