### ISSUE TITLE
[feature request] add auth to server by public key as alternative to user/pass

### ISSUE THREAD

**Issue by lgg** [amnezia-vpn/desktop-client#8]
I want to use Amnezia on VPS with other hosted services and for security reasons i have enabled only pubkey auth on SSH. I wish Amnezia to have support for pubkey auth on SSH as alternative to Password auth.

**Comment by lgg** [comment]
@pokamest it's broken url for `.exe` file 0o

I see only MacOS and Windows binaries: 
![image](https://user-images.githubusercontent.com/12018713/111348944-be899680-8691-11eb-8786-5665870b126e.png)

**Comment by pokamest** [comment]
1.5.1 Released (Windows only)
https://github.com/amnezia-vpn/desktop-client/releases/download/1.5/AmneziaVPN_1.5.1.exe

**Comment by bessgeor** [comment]
Just downloaded Amnezia VPN from the amnezia.org and tried to authenticate via key pair. As a result I'm getting the following error: ![image](https://user-images.githubusercontent.com/2414765/113392107-44e5ee00-939d-11eb-9d9f-ee8deb9e418c.png)

I could authenticate using the same credentials by using WSL, the difference is that ssh command requests private key password and amnezia vpn does not.

**Comment by Straven** [comment]
Amnezia can't connect not with private key neither with public. But all ssh-clients and tool succesfully authenticated. Fix problem pls. Password auth is not good.

**Comment by pokamest** [comment]
Private keys encrypted with password is not supported.
If you are experiencing problems with authentication via keys try to convert your keys into PEM format using ssh-keygen utility.
`ssh-keygen -p -P "" -N "" -m pem -f path_you_private_key`
Do backup of your private key or convert a copy - ssh-keygen will replace file.

Please provide more information about your private key - what is key format you using? I need to know just header of your key - like "-----BEGIN RSA PRIVATE KEY-----". Don't send whole key.

**Comment by Straven** [comment]
yeah. my mistake was i not add header to input field. with header all works fine

**Comment by pokamest** [comment]
Issue fixed since 1.5.3
